version: "3.9"
services:
  app:
    container_name: azurenamingtool
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ../..:/workspaces:cached
      - azurenamingtoolvol:/app/settings
      # - azurenamingtoolvol:../
volumes:
  azurenamingtoolvol:
  # - ../..:/workspaces:cached
  # - ../:/app/settings
  # - azurenamingtoolvol:/app/settings
